language: python
os: linux
install: pip install --no-cache-dir -U tox-travis
script: tox
python:
- 3.8
- 3.7
- 3.6
jobs:
  include:
  - stage: test
    name: Measure code coverage
    install: pip install --no-cache-dir -U tox-travis
    script: tox -e codecov
    python: 3.6
  - stage: deploy
    name: Deploy to PyPI
    script: pip install --no-cache-dir -e .
    python: 3.6
    deploy:
      provider: pypi
      username: __token__
      skip_cleanup: true
      password:
        secure: TDf07PoBI5KFfgpN1boMMk8Mu/vTus2yi428URkr/2bDOwYhIGEXdDlL76whRUb3zpBL+cfXDJVz5t7ldMD83CrT2PaoPgHsc8mDviSlUdSPJJ6dXeUT1p5RBPKGH43aqU4buyOHI1OCvuX/F7qpY0xoOZruxbQbxU/0j0Djjqt7ZznP/GqfFtNweMkw4XikiQa5rrVAQ65CXiZttSSE6ccll7LRfg5m1fPovKfKYR1G6O6KlNdJ7ISUxepjhr3BAUFUQt6k8kvyB3UC8MBy+OOy3HKPGmTg53j0WzDqkXU10fydC+zW8vPUeGR25cOeXCGBsdPvvqfU07jUqxTk/A5Pj1KDig3y4mEABL85Jwh3S3AsoSEYhe1m9Z9Hgecra0whHr6TvSXBvzvJzo1HY0FXJ892s9ijF6RwfCfKwvICqgKNze0vJBumskWUUvnhCAog7v0hFSajVgKMPyToTOLNk3VI+NCc2uV06JjdL9jziSWrXjzFdALyLBIY0B8KpcQbsBNxLuWbyMc6927lmZLbsmyKi3u+MacjwftDekT6GKkNRkvldnLKLqYOL/6QnO7MNjn9J6Dvoe6Z1v0TzoA2++N+6PoRxnQvIQ7lPPTkeY8KSpxxxYoFUvazxHgMc7cQIc4C7JsqpTcjAIcKlgY8taQtWMEx8d27kcndFLY=
      on:
        tags: true
        python: 3.6
